namespace GameServer.Application.DTOs.Game;

public class GameDto { public Guid Id{get;set;} public string Name{get;set;}=""; public string Description{get;set;}=""; public string Type{get;set;}=""; public int MaxPlayers{get;set;} public int MinPlayers{get;set;} public bool IsActive{get;set;} public string? MapName{get;set;} public int DurationSeconds{get;set;} public int RewardCoins{get;set;} public int RewardExperience{get;set;} public string? IconUrl{get;set;} }
public class GameSessionDto { public Guid Id{get;set;} public Guid GameId{get;set;} public string GameName{get;set;}=""; public string SessionCode{get;set;}=""; public string Status{get;set;}=""; public int CurrentPlayers{get;set;} public int MaxPlayers{get;set;} public string? ServerRegion{get;set;} public DateTime? StartedAt{get;set;} public DateTime? EndedAt{get;set;} public IEnumerable<ParticipantDto> Participants{get;set;}=new List<ParticipantDto>(); public DateTime CreatedAt{get;set;} }
public class ParticipantDto { public Guid UserId{get;set;} public string Username{get;set;}=""; public string? AvatarUrl{get;set;} public int Score{get;set;} public int Kills{get;set;} public int Deaths{get;set;} public string? Result{get;set;} public bool IsHost{get;set;} }
public class CreateSessionDto { public Guid GameId{get;set;} public string? ServerRegion{get;set;} }
public class EndSessionDto { public List<ParticipantResultDto> Results{get;set;}=new(); }
public class ParticipantResultDto { public Guid UserId{get;set;} public int Score{get;set;} public int Kills{get;set;} public int Deaths{get;set;} public string Result{get;set;}=""; }
public class GameHistoryDto { public Guid SessionId{get;set;} public string GameName{get;set;}=""; public string? MapName{get;set;} public string Result{get;set;}=""; public int Score{get;set;} public int Kills{get;set;} public int Deaths{get;set;} public int CoinsEarned{get;set;} public int ExperienceEarned{get;set;} public DateTime PlayedAt{get;set;} public int DurationSeconds{get;set;} }
public class PagedResultDto<T> { public IEnumerable<T> Items{get;set;}=new List<T>(); public int TotalCount{get;set;} public int Page{get;set;} public int PageSize{get;set;} public int TotalPages=>TotalCount==0?0:(int)Math.Ceiling((double)TotalCount/PageSize); public bool HasNextPage=>Page<TotalPages; public bool HasPreviousPage=>Page>1; }
