using GameServer.Application.DTOs.Game;
namespace GameServer.Application.DTOs.Admin;

public class AdminUserDto { public Guid Id{get;set;} public string Username{get;set;}=""; public string Email{get;set;}=""; public string Role{get;set;}=""; public string Status{get;set;}=""; public string? FirstName{get;set;} public string? LastName{get;set;} public string? Country{get;set;} public bool IsEmailVerified{get;set;} public DateTime? LastLoginAt{get;set;} public string? LastLoginIp{get;set;} public DateTime CreatedAt{get;set;} public string? BanReason{get;set;} public DateTime? BannedAt{get;set;} public int TotalGamesPlayed{get;set;} public int Level{get;set;} public int Coins{get;set;} public int Gems{get;set;} }
public class AdminUserFilterDto { public string? Search{get;set;} public string? Role{get;set;} public string? Status{get;set;} public int Page{get;set;}=1; public int PageSize{get;set;}=20; public string SortBy{get;set;}="CreatedAt"; public string SortDirection{get;set;}="desc"; }
public class BanUserDto { public string Reason{get;set;}=""; }
public class AdminDashboardDto { public int TotalUsers{get;set;} public int ActiveUsers{get;set;} public int BannedUsers{get;set;} public int TotalGames{get;set;} public int ActiveSessions{get;set;} public int NewUsersToday{get;set;} public int NewUsersThisWeek{get;set;} public int NewUsersThisMonth{get;set;} public IEnumerable<TopPlayerDto> TopPlayers{get;set;}=new List<TopPlayerDto>(); }
public class TopPlayerDto { public Guid UserId{get;set;} public string Username{get;set;}=""; public int Level{get;set;} public int RankPoints{get;set;} public int TotalWins{get;set;} }
public class CreditCurrencyDto { public Guid UserId{get;set;} public int CoinsAmount{get;set;}=0; public int GemsAmount{get;set;}=0; public string Reason{get;set;}=""; }
public class AuditLogDto { public Guid Id{get;set;} public Guid UserId{get;set;} public string Username{get;set;}=""; public string Action{get;set;}=""; public string? IpAddress{get;set;} public string? Details{get;set;} public Guid? PerformedByAdminId{get;set;} public DateTime CreatedAt{get;set;} }
public class SendNotificationDto { public Guid? UserId{get;set;} public string Title{get;set;}=""; public string Message{get;set;}=""; public string Type{get;set;}="info"; public string? ActionUrl{get;set;} }
public class CreateGameDto { public string Name{get;set;}=""; public string Description{get;set;}=""; public string Type{get;set;}="Solo"; public int MaxPlayers{get;set;}=10; public int MinPlayers{get;set;}=1; public string? MapName{get;set;} public int DurationSeconds{get;set;}=300; public int RewardCoins{get;set;}=100; public int RewardExperience{get;set;}=200; public string? IconUrl{get;set;} }
public class UpdateGameDto:CreateGameDto { public bool IsActive{get;set;}=true; }
public class SystemSettingDto { public Guid Id{get;set;} public string Key{get;set;}=""; public string Value{get;set;}=""; public string? Description{get;set;} public bool IsPublic{get;set;} }
